package controller;

import config.Database;
import jakarta.servlet.annotation.WebServlet;
import jakarta.servlet.http.*;
import java.io.IOException;
import java.math.BigDecimal;
import java.sql.*;
import java.util.*;

@WebServlet(urlPatterns={"/api/invoices","/api/invoices/*"})
public class InvoiceServlet extends BaseServlet {
    private static final List<String> STATUSES=List.of("Đã thanh toán","Chưa thanh toán","Đang xử lý","Đã hủy","Quá hạn");
    @Override protected void service(HttpServletRequest req,HttpServletResponse resp)throws jakarta.servlet.ServletException,IOException{req.setCharacterEncoding("UTF-8");resp.setCharacterEncoding("UTF-8");super.service(req,resp);}
    @Override protected void doGet(HttpServletRequest req,HttpServletResponse resp)throws IOException{Path path=path(req);if(path.id==null)list(req,resp);else detail(path.id,resp);}
    @Override protected void doPost(HttpServletRequest req,HttpServletResponse resp)throws IOException{Path path=path(req);if(path.id!=null&&"pay".equals(path.action))pay(path.id,req,resp);else if(path.id==null)save(null,req,resp);else writeJson(resp,404,jsonMap("message","Đường dẫn không hợp lệ"));}
    @Override protected void doPut(HttpServletRequest req,HttpServletResponse resp)throws IOException{Path path=path(req);if(path.id==null){writeJson(resp,400,jsonMap("message","Thiếu mã hóa đơn"));return;}save(path.id,req,resp);}
    @Override protected void doDelete(HttpServletRequest req,HttpServletResponse resp)throws IOException{Path path=path(req);if(path.id==null){writeJson(resp,400,jsonMap("message","Thiếu mã hóa đơn"));return;}try(Connection c=Database.getConnection();PreparedStatement ps=c.prepareStatement("DELETE FROM invoices WHERE id=?")){ps.setInt(1,path.id);if(ps.executeUpdate()==0){writeJson(resp,404,jsonMap("message","Không tìm thấy hóa đơn"));return;}writeJson(resp,jsonMap("success",true,"message","Xóa hóa đơn thành công"));}catch(SQLException e){error("Không thể xóa hóa đơn",e,resp);}}

    private void list(HttpServletRequest req,HttpServletResponse resp)throws IOException{int page=Math.max(parse(req.getParameter("page"),1),1),limit=Math.min(Math.max(parse(req.getParameter("limit"),10),1),100),offset=(page-1)*limit;List<String>w=new ArrayList<>();List<Object>p=new ArrayList<>();String search=trim(req.getParameter("search"));if(search!=null){w.add("(i.invoice_code LIKE ? OR s.full_name LIKE ? OR r.room_code LIKE ?)");String k="%"+search+"%";p.add(k);p.add(k);p.add(k);}filter(w,p,"i.status=?",req.getParameter("status"));filter(w,p,"b.id=?",req.getParameter("building_id"));filter(w,p,"r.id=?",req.getParameter("room_id"));filter(w,p,"DATE(i.created_at)>=?",req.getParameter("from"));filter(w,p,"DATE(i.created_at)<=?",req.getParameter("to"));String where=w.isEmpty()?"":" WHERE "+String.join(" AND ",w);String joins=" FROM invoices i JOIN students s ON s.id=i.student_id LEFT JOIN rooms r ON r.id=s.room_id LEFT JOIN buildings b ON b.id=r.building_id ";String select="SELECT i.*,s.student_code,s.full_name,r.room_code,b.building_name "+joins+where+" ORDER BY i.created_at DESC,i.id DESC LIMIT ? OFFSET ?";try(Connection c=Database.getConnection()){int total;try(PreparedStatement ps=c.prepareStatement("SELECT COUNT(*) "+joins+where)){setParams(ps,p);try(ResultSet rs=ps.executeQuery()){rs.next();total=rs.getInt(1);}}List<Object>lp=new ArrayList<>(p);lp.add(limit);lp.add(offset);List<Map<String,Object>>items;try(PreparedStatement ps=c.prepareStatement(select)){setParams(ps,lp);try(ResultSet rs=ps.executeQuery()){items=rows(rs);}}Map<String,Object>stats;try(PreparedStatement ps=c.prepareStatement("SELECT COUNT(*) total,SUM(status='Đã thanh toán') paid,SUM(status IN ('Chưa thanh toán','Quá hạn')) unpaid,COALESCE(SUM(CASE WHEN status='Đã thanh toán' THEN total_amount ELSE 0 END),0) revenue FROM invoices");ResultSet rs=ps.executeQuery()){rs.next();stats=row(rs);}List<Map<String,Object>>buildings;try(PreparedStatement ps=c.prepareStatement("SELECT COALESCE(b.building_name,'Chưa phân tòa') label,COALESCE(SUM(i.total_amount),0) total FROM invoices i JOIN students s ON s.id=i.student_id LEFT JOIN rooms r ON r.id=s.room_id LEFT JOIN buildings b ON b.id=r.building_id GROUP BY b.id,b.building_name ORDER BY total DESC");ResultSet rs=ps.executeQuery()){buildings=rows(rs);}writeJson(resp,jsonMap("invoices",items,"total",total,"page",page,"limit",limit,"stats",stats,"building_revenue",buildings));}catch(SQLException e){error("Không tải được danh sách hóa đơn",e,resp);}}
    private void detail(int id,HttpServletResponse resp)throws IOException{String sql="SELECT i.*,s.student_code,s.full_name,s.phone,s.email,r.room_code,b.building_name FROM invoices i JOIN students s ON s.id=i.student_id LEFT JOIN rooms r ON r.id=s.room_id LEFT JOIN buildings b ON b.id=r.building_id WHERE i.id=?";try(Connection c=Database.getConnection();PreparedStatement ps=c.prepareStatement(sql)){ps.setInt(1,id);try(ResultSet rs=ps.executeQuery()){if(!rs.next()){writeJson(resp,404,jsonMap("message","Không tìm thấy hóa đơn"));return;}writeJson(resp,row(rs));}}catch(SQLException e){error("Không tải được chi tiết hóa đơn",e,resp);}}
    private void save(Integer id,HttpServletRequest req,HttpServletResponse resp)throws IOException{try{Map<String,Object>b=readJson(req);Integer student=integer(b,"student_id");String period=text(b,"billing_period"),status=text(b,"status"),method=text(b,"payment_method"),note=text(b,"note");BigDecimal electricity=decimal(b.get("electricity_amount")),water=decimal(b.get("water_amount")),service=decimal(b.get("service_amount"));java.sql.Date due=date(b,"due_date");if(student==null||period==null||due==null||!STATUSES.contains(status)||electricity==null||water==null||service==null||electricity.signum()<0||water.signum()<0||service.signum()<0){writeJson(resp,400,jsonMap("message","Vui lòng kiểm tra sinh viên, kỳ thanh toán, ngày hạn, số tiền và trạng thái"));return;}BigDecimal total=electricity.add(water).add(service);if(id==null)create(student,period,electricity,water,service,total,status,method,note,due,resp);else update(id,student,period,electricity,water,service,total,status,method,note,due,resp);}catch(IllegalArgumentException e){writeJson(resp,400,jsonMap("message",e.getMessage()));}catch(SQLException e){error("Không thể lưu hóa đơn",e,resp);}}
    private void create(int student,String period,BigDecimal electricity,BigDecimal water,BigDecimal service,BigDecimal total,String status,String method,String note,java.sql.Date due,HttpServletResponse resp)throws SQLException,IOException{try(Connection c=Database.getConnection()){c.setAutoCommit(false);try(PreparedStatement ps=c.prepareStatement("INSERT INTO invoices(invoice_code,student_id,billing_period,electricity_amount,water_amount,service_amount,total_amount,status,payment_method,note,due_date,paid_at) VALUES(?,?,?,?,?,?,?,?,?,?,?,?)",Statement.RETURN_GENERATED_KEYS)){ps.setString(1,"TMP"+System.nanoTime());bind(ps,2,student,period,electricity,water,service,total,status,method,note,due);ps.executeUpdate();try(ResultSet keys=ps.getGeneratedKeys()){keys.next();int id=keys.getInt(1);String code="HD"+String.format("%07d",id);try(PreparedStatement update=c.prepareStatement("UPDATE invoices SET invoice_code=? WHERE id=?")){update.setString(1,code);update.setInt(2,id);update.executeUpdate();}c.commit();writeJson(resp,201,jsonMap("success",true,"id",id,"invoice_code",code,"message","Tạo hóa đơn thành công"));}}catch(Exception e){c.rollback();throw e;}finally{c.setAutoCommit(true);}}}
    private void update(int id,int student,String period,BigDecimal electricity,BigDecimal water,BigDecimal service,BigDecimal total,String status,String method,String note,java.sql.Date due,HttpServletResponse resp)throws SQLException,IOException{try(Connection c=Database.getConnection();PreparedStatement ps=c.prepareStatement("UPDATE invoices SET student_id=?,billing_period=?,electricity_amount=?,water_amount=?,service_amount=?,total_amount=?,status=?,payment_method=?,note=?,due_date=?,paid_at=CASE WHEN ?='Đã thanh toán' THEN COALESCE(paid_at,NOW()) ELSE NULL END WHERE id=?")){bind(ps,1,student,period,electricity,water,service,total,status,method,note,due);ps.setString(11,status);ps.setInt(12,id);if(ps.executeUpdate()==0){writeJson(resp,404,jsonMap("message","Không tìm thấy hóa đơn"));return;}writeJson(resp,jsonMap("success",true,"message","Cập nhật hóa đơn thành công"));}}
    private void bind(PreparedStatement ps,int start,int student,String period,BigDecimal electricity,BigDecimal water,BigDecimal service,BigDecimal total,String status,String method,String note,java.sql.Date due)throws SQLException{ps.setInt(start,student);ps.setString(start+1,period);ps.setBigDecimal(start+2,electricity);ps.setBigDecimal(start+3,water);ps.setBigDecimal(start+4,service);ps.setBigDecimal(start+5,total);ps.setString(start+6,status);ps.setString(start+7,method);ps.setString(start+8,note);ps.setDate(start+9,due);if(start==2){if("Đã thanh toán".equals(status))ps.setTimestamp(start+10,new Timestamp(System.currentTimeMillis()));else ps.setNull(start+10,Types.TIMESTAMP);}}
    private void pay(int id,HttpServletRequest req,HttpServletResponse resp)throws IOException{try{Map<String,Object>b=readJson(req);String method=text(b,"payment_method");if(method==null){writeJson(resp,400,jsonMap("message","Vui lòng chọn phương thức thanh toán"));return;}try(Connection c=Database.getConnection();PreparedStatement ps=c.prepareStatement("UPDATE invoices SET status='Đã thanh toán',payment_method=?,paid_at=NOW() WHERE id=? AND status<>'Đã hủy'")){ps.setString(1,method);ps.setInt(2,id);if(ps.executeUpdate()==0){writeJson(resp,409,jsonMap("message","Hóa đơn không tồn tại hoặc đã hủy"));return;}writeJson(resp,jsonMap("success",true,"message","Xác nhận thanh toán thành công"));}}catch(SQLException e){error("Không thể xác nhận thanh toán",e,resp);}}
    private BigDecimal decimal(Object value){try{return value==null?null:new BigDecimal(String.valueOf(value));}catch(Exception e){return null;}}private java.sql.Date date(Map<String,Object>b,String key){String v=text(b,key);if(v==null)return null;try{return java.sql.Date.valueOf(v);}catch(Exception e){throw new IllegalArgumentException("Ngày không hợp lệ");}}private void filter(List<String>w,List<Object>p,String sql,String value){String v=trim(value);if(v!=null){w.add(sql);p.add(v);}}private String trim(String v){return v==null||v.trim().isEmpty()?null:v.trim();}private int parse(String v,int f){try{return v==null?f:Integer.parseInt(v);}catch(Exception e){return f;}}private void error(String message,Exception e,HttpServletResponse resp)throws IOException{getServletContext().log(message,e);writeJson(resp,500,jsonMap("message",message));}private Path path(HttpServletRequest req){String v=req.getPathInfo();if(v==null||v.equals("/")||v.isBlank())return new Path(null,null);String[]p=v.substring(1).split("/");try{return new Path(Integer.valueOf(p[0]),p.length>1?p[1]:null);}catch(Exception e){return new Path(null,"invalid");}}private record Path(Integer id,String action){}
}
