(() => {
 const context=window.APP_CONTEXT||"",api=`${context}/api/settings`,$=s=>document.querySelector(s),esc=v=>String(v??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[c]));
 function create(){if($("#settingsView"))return;const view=document.createElement("section");view.id="settingsView";view.className="view";view.innerHTML=`<div class="section-title"><h2>Cài đặt hệ thống</h2><p>Trang chủ / Hệ thống / Cài đặt hệ thống</p></div><div class="settings-layout"><section class="settings-card"><header class="settings-card-head"><i class="fa-solid fa-sliders"></i><div><h2>Thông tin chung</h2><p>Thông tin hiển thị của hệ thống và ký túc xá</p></div></header><form class="settings-form" id="generalSettingsForm"><label>Tên hệ thống *<input name="system_name" maxlength="200" required></label><label>Tên ký túc xá *<input name="dormitory_name" maxlength="200" required></label><label class="wide">Địa chỉ<input name="address" maxlength="500"></label><label>Email<input name="email" type="email" maxlength="100"></label><label>Số điện thoại<input name="phone" maxlength="20"></label><label class="wide">Footer<input name="footer" maxlength="500"></label><div class="wide settings-logo-preview"><img src="${context}/logo/Logo.png.jpg" alt="Logo ký túc xá"><div><strong>Logo hiện tại</strong><p class="settings-note">Project đang sử dụng logo tĩnh. Giữ nguyên để bảo đảm file không mất sau khi redeploy WAR.</p></div></div><div class="settings-actions"><button type="button" class="secondary" id="settingsReload">Tải lại</button><button class="primary" type="submit"><i class="fa-solid fa-floppy-disk"></i>Lưu thông tin</button></div></form></section><div class="settings-side"><section class="settings-card"><header class="settings-card-head"><i class="fa-solid fa-key"></i><div><h2>Đổi mật khẩu</h2><p>Mật khẩu mới được mã hóa bằng BCrypt</p></div></header><form class="settings-form" id="passwordSettingsForm"><label class="wide">Mật khẩu hiện tại<input name="old_password" type="password" required autocomplete="current-password"></label><label class="wide">Mật khẩu mới<input name="new_password" type="password" minlength="6" required autocomplete="new-password"></label><label class="wide">Xác nhận mật khẩu<input name="confirm_password" type="password" minlength="6" required autocomplete="new-password"></label><div class="settings-actions"><button class="primary" type="submit">Đổi mật khẩu</button></div></form></section><section class="settings-card"><header class="settings-card-head"><i class="fa-regular fa-bell"></i><div><h2>Thông báo chung</h2><p>Nội dung thông báo dành cho người sử dụng</p></div></header><form class="settings-form" id="announcementSettingsForm"><label class="wide">Nội dung thông báo<textarea name="announcement" maxlength="2000" placeholder="Nhập thông báo chung..."></textarea></label><div class="settings-actions"><button class="primary" type="submit">Lưu thông báo</button></div></form></section></div></div><div class="settings-toast" id="settingsToast"></div>`;$(".main").appendChild(view);bind();}
 async function request(url,options={}){const res=await fetch(url,{cache:"no-store",...options}),data=await res.json().catch(()=>({}));if(!res.ok)throw new Error(data.message||`Lỗi API (${res.status})`);return data;}
 async function load(){try{const data=await request(api);for(const [key,value] of Object.entries(data)){const field=document.querySelector(`[name="${CSS.escape(key)}"]`);if(field)field.value=value||"";}}catch(e){toast(e.message,"error")}}
 async function save(form,keys){const all=Object.fromEntries(new FormData(form).entries()),body={};keys.forEach(k=>body[k]=all[k]||"");await request(api,{method:"PUT",headers:{"Content-Type":"application/json; charset=UTF-8"},body:JSON.stringify(body)});toast("Lưu cài đặt thành công")}
 function bind(){$("#generalSettingsForm").onsubmit=async e=>{e.preventDefault();try{await save(e.currentTarget,["system_name","dormitory_name","address","email","phone","footer"])}catch(x){toast(x.message,"error")}};$("#announcementSettingsForm").onsubmit=async e=>{e.preventDefault();try{await save(e.currentTarget,["announcement"])}catch(x){toast(x.message,"error")}};$("#settingsReload").onclick=load;$("#passwordSettingsForm").onsubmit=async e=>{e.preventDefault();const body=Object.fromEntries(new FormData(e.currentTarget).entries());if(body.new_password!==body.confirm_password){toast("Mật khẩu xác nhận không khớp","error");return;}try{await request(`${api}/password`,{method:"POST",headers:{"Content-Type":"application/json; charset=UTF-8"},body:JSON.stringify(body)});e.currentTarget.reset();toast("Đổi mật khẩu thành công")}catch(x){toast(x.message,"error")}}}
 function toast(message,type="success"){const t=$("#settingsToast");t.textContent=message;t.className=`settings-toast show ${type}`;clearTimeout(toast.timer);toast.timer=setTimeout(()=>t.classList.remove("show"),3200)}
 window.enableSettingsSidebar=()=>{const item=[...document.querySelectorAll("#sidebarContainer .menu-item")].find(el=>el.textContent.includes("Cài đặt hệ thống"));if(item){item.dataset.view="settings";item.classList.remove("muted")}};window.renderSettingsView=()=>{create();load()};document.addEventListener("DOMContentLoaded",create);
})();
